--СТВОРЕННЯ ТАБЛИЦЬ--
-- 1. Таблиця Employers (Роботодавці)
CREATE TABLE Employers (
    employer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(150) NOT NULL,
    legal_form VARCHAR2(50) CHECK (legal_form IN ('ТОВ', 'ПАТ', 'ПрАТ', 'ФОП', 'Фізична особа', 'ДП', 'КОП', 'ПП', 'КП', 'ТДВ', 'Громадська організація', 'Благодійна організація', 'Інше')),
    industry VARCHAR2(100),
    address VARCHAR2(200),
    website VARCHAR2(100),
    about CLOB,
    founded_year NUMBER(4),
    employee_count NUMBER CHECK (employee_count >= 0),
    is_verified CHAR(1) CHECK (is_verified IN('Y', 'N')),
    is_active CHAR(1) DEFAULT'Y' CHECK(is_active IN('Y','N'))
);


-- 2. Таблиця Contacts (Контакти роботодавців)
CREATE TABLE Contacts (
    contact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id NUMBER NOT NULL,
    contact_name VARCHAR2(100),
    position VARCHAR2(100),
    --Один номер телефону/email для кількох контактів(HR-відділ напркилад)
    phone VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    is_primary CHAR(1) CHECK (is_primary IN ('Y', 'N')),
    CONSTRAINT fk_contacts_employer FOREIGN KEY (employer_id) REFERENCES Employers(employer_id) ON DELETE CASCADE
);

-- 3. Таблиця Specialties (Спеціальності)
CREATE TABLE Specialties (
    specialty_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_name VARCHAR2(100) NOT NULL UNIQUE,
    category VARCHAR2(80),
    allow_age_restriction CHAR(1) DEFAULT 'N' CHECK(allow_age_restriction IN ('N','Y'))
);

-- 4. Таблиця Cities (Міста)
CREATE TABLE Cities (
    city_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR2(80) NOT NULL,
    region VARCHAR2(80),
    CONSTRAINT unq_city_region UNIQUE (city_name, region)
);

-- 5. Таблиця Vacancies (Вакансії)
CREATE TABLE Vacancies (
    vacancy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id NUMBER NOT NULL,
    title VARCHAR2(150) NOT NULL,
    specialty_id NUMBER NOT NULL,
    salary_min NUMBER(10,2),
    salary_max NUMBER(10,2),
    experience_required NUMBER(2) DEFAULT 0 CHECK(experience_required >=0 AND experience_required<=50),
    education_level VARCHAR2(50),
    age_min NUMBER(2) CHECK (age_min >= 16),
    age_max NUMBER(2),
    work_schedule VARCHAR2(50) CHECK (work_schedule IN ('Full-time', 'Part-time', 'Remote', 'Flexible')),
    description CLOB,
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('N', 'Y')),
    published_date DATE DEFAULT SYSDATE,
    ---- Для Vacancies НЕ додаєм CASCADE (зберігаємо історію)
    -- при спробі видалити Employers Вакансія стає неактивною
    CONSTRAINT fk_vacancies_employer FOREIGN KEY (employer_id) REFERENCES Employers(employer_id),
    CONSTRAINT fk_vacancies_specialty FOREIGN KEY (specialty_id) REFERENCES Specialties(specialty_id),
    CONSTRAINT chk_salary CHECK(salary_min<=salary_max),
    CONSTRAINT chk_age_range CHECK (age_min <= age_max)
);

-- 6. Таблиця Vacancy_Cities (Міста_Вакансії)
CREATE TABLE Vacancy_Cities (
    vacancy_id NUMBER NOT NULL,
    city_id NUMBER NOT NULL,
    CONSTRAINT pk_vacancy_cities PRIMARY KEY (vacancy_id, city_id),
    CONSTRAINT fk_vacancy_cities_vacancy FOREIGN KEY (vacancy_id) REFERENCES Vacancies(vacancy_id) ON DELETE CASCADE,
    -- Cities слугує довідником і їх майже не видаляють на відміну від Вакансій(не ставимо ON DELETE CASCADE)
    CONSTRAINT fk_vacancy_cities_city FOREIGN KEY (city_id) REFERENCES Cities(city_id) 
);

-- 7. Таблиця Candidates (Кандидати)
CREATE TABLE Candidates (
    candidate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    middle_name VARCHAR2(50),
    last_name VARCHAR2(50) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR2(20) NOT NULL UNIQUE,
    email VARCHAR2(100) UNIQUE,
    city_id NUMBER,
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('N', 'Y')),
    relocation_possible CHAR(1) DEFAULT '0' CHECK (relocation_possible IN ('0', '1', '2')),
    -- total_experience зберігається для спрощення перевірок, можна обчислювати на рівні додатку
    total_experience_years NUMBER DEFAULT 0,
    CONSTRAINT fk_candidates_city FOREIGN KEY (city_id) REFERENCES Cities(city_id)
);

-- 8. Таблиця Resumes (Резюме)
CREATE TABLE Resumes (
    resume_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id NUMBER NOT NULL,
    title VARCHAR2(150) NOT NULL,
    specialty_id NUMBER,
    desired_salary NUMBER(10,2),
    about CLOB,
    created_date DATE DEFAULT SYSDATE,
    is_visible CHAR(1) DEFAULT 'Y' CHECK (is_visible IN ('N', 'Y')),
    CONSTRAINT fk_resumes_candidate FOREIGN KEY (candidate_id) REFERENCES Candidates(candidate_id) ON DELETE CASCADE,
    CONSTRAINT fk_resumes_specialty FOREIGN KEY (specialty_id) REFERENCES Specialties(specialty_id)
);

-- 9. Таблиця Educations (Освіта)
CREATE TABLE Educations (
    education_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id NUMBER NOT NULL,
    institution VARCHAR2(150) NOT NULL,
    faculty VARCHAR2(100),
    specialty VARCHAR2(100),
    degree VARCHAR2(50) CHECK (degree IN ('Повна загальна середня освіта', 'Фаховий молодший бакалавр', 'Молодший бакалавр', 'Бакалавр', 'Магістр', 'Спеціаліст', 'Доктор філософії', 'Доктор наук')),
    start_year NUMBER(4) CHECK (start_year >= 1950),
    is_current CHAR(1) CHECK (is_current IN ('Y', 'N')),
    current_year NUMBER(1) CHECK (current_year BETWEEN 1 AND 6 OR current_year IS NULL),
    graduation_year NUMBER(4),
    CONSTRAINT chk_graduation_year CHECK (graduation_year >= start_year),
    CONSTRAINT fk_educations_resume FOREIGN KEY (resume_id) REFERENCES Resumes(resume_id) ON DELETE CASCADE
);

-- 10. Таблиця Work_Experience (Досвід роботи)
CREATE TABLE Work_Experience (
    experience_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id NUMBER NOT NULL,
    company_name VARCHAR2(150) NOT NULL,
    position VARCHAR2(100) NOT NULL,
    start_date DATE NOT NULL CHECK(start_date >= DATE '1950-01-01'),
    end_date DATE,
    is_current CHAR(1) DEFAULT 'N' CHECK (is_current IN ('N', 'Y')),
    responsibilities CLOB,
    CONSTRAINT fk_work_experience_resume FOREIGN KEY (resume_id) REFERENCES Resumes(resume_id) ON DELETE CASCADE,
    CONSTRAINT chk_start_end_date CHECK (start_date <= end_date OR end_date IS NULL),
    CONSTRAINT chk_current_employment CHECK (NOT (is_current = 'Y' AND end_date IS NOT NULL))
);

-- 11. Таблиця Skills (Навички)
CREATE TABLE Skills (
    skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR2(80) NOT NULL UNIQUE
);

-- 12. Таблиця Resume_Skills (Навички в резюме)
CREATE TABLE Resume_Skills (
    resume_id NUMBER NOT NULL,
    skill_id NUMBER NOT NULL,
    skill_level VARCHAR2(20) CHECK (skill_level IN ('Початковий', 'Середній', 'Просунутий', 'Експерт')),
    CONSTRAINT pk_resume_skills PRIMARY KEY (resume_id, skill_id),
    CONSTRAINT fk_resume_skills_resume FOREIGN KEY (resume_id) REFERENCES Resumes(resume_id) ON DELETE CASCADE,
    --не додаємо ON DELETE CASCADE бо скіли це довідник і потрібно для статистики або історії
    CONSTRAINT fk_resume_skills_skill FOREIGN KEY (skill_id) REFERENCES Skills(skill_id)
);

-- Таблиця Application_Status (Статус відгуку)
CREATE TABLE Application_Status (
    application_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_status_name VARCHAR2(50) NOT NULL UNIQUE
);
-- Таблиця Interview_Status (Статус співбесіди)
CREATE TABLE Interview_Status (
    interview_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_status_name VARCHAR2(50) NOT NULL UNIQUE
);
-- Таблиця Interview_Types (Тип співбесіди)
CREATE TABLE Interview_Types (
    interview_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_type_name VARCHAR2(50) NOT NULL UNIQUE
);

-- 13. Таблиця Applications (Відгуки)
CREATE TABLE Applications (
    application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id NUMBER NOT NULL,
    vacancy_id NUMBER NOT NULL,
    applied_date DATE DEFAULT SYSDATE,
    application_status_id NUMBER,
    cover_letter CLOB,
    CONSTRAINT fk_applications_resume FOREIGN KEY (resume_id) REFERENCES Resumes(resume_id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_vacancy FOREIGN KEY (vacancy_id) REFERENCES Vacancies(vacancy_id),
    CONSTRAINT fk_applications_status FOREIGN KEY (application_status_id) REFERENCES Application_Status(application_status_id),
    CONSTRAINT uk_application_unique UNIQUE (resume_id, vacancy_id)
);

-- 14. Таблиця Interviews (Співбесіди)
CREATE TABLE Interviews (
    interview_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER NOT NULL,
    interview_type_id NUMBER NOT NULL,
    interview_date DATE,
    duration_minutes NUMBER(3) CHECK (duration_minutes BETWEEN 15 AND 120),
    interviewer VARCHAR2(100) NOT NULL,
    interview_status_id NUMBER,
    notes CLOB,
    CONSTRAINT fk_interviews_application FOREIGN KEY (application_id) REFERENCES Applications(application_id) ON DELETE CASCADE,
    CONSTRAINT fk_interviews_type FOREIGN KEY (interview_type_id) REFERENCES Interview_Types(interview_type_id),
    CONSTRAINT fk_interviews_status FOREIGN KEY (interview_status_id) REFERENCES Interview_Status(interview_status_id)
);


DESC Vacancies
SELECT 
    constraint_name,
    constraint_type,
    search_condition
FROM user_constraints
WHERE table_name = 'VACANCIES';

--ВСІ ТАБЛИЦІ
SELECT table_name
FROM user_tables
ORDER BY table_name;

--ОБМЕЖЕННЯ
SELECT 
    uc.table_name,
    uc.constraint_name,
    uc.constraint_type,
    uc.search_condition
FROM user_constraints uc
WHERE uc.constraint_type IN ('P', 'R', 'C', 'U')
ORDER BY uc.table_name, uc.constraint_type;




SELECT constraint_name, search_condition
FROM user_constraints
WHERE table_name = 'SPECIALTIES'
  AND constraint_type = 'C';


ALTER TABLE Specialties
DROP CONSTRAINT SYS_C008575;

